export const NEW_CAT_REQUEST = "NEW_CAT_REQUEST";
export const NEW_CAT_SUCCESS = "NEW_CAT_SUCCESS";
export const NEW_CAT_RESET = "NEW_CAT_RESET";
export const NEW_CAT_FAIL = "NEW_CAT_FAIL";

export const CAT_DETAILS_REQUEST = "CAT_DETAILS_REQUEST";
export const CAT_DETAILS_SUCCESS = "CAT_DETAILS_SUCCESS";
export const CAT_DETAILS_FAIL = "CAT_DETAILS_FAIL";

export const ALL_CAT_REQUEST = "ALL_CAT_REQUEST";
export const ALL_CAT_SUCCESS = "ALL_CAT_SUCCESS";
export const ALL_CAT_FAIL = "ALL_CAT_FAIL";

export const UPDATE_CAT_REQUEST = "UPDATE_CAT_REQUEST";
export const UPDATE_CAT_SUCCESS = "UPDATE_CAT_SUCCESS";
export const UPDATE_CAT_RESET = "UPDATE_CAT_RESET";
export const UPDATE_CAT_FAIL = "UPDATE_CAT_FAIL";

export const DELETE_CAT_REQUEST = "DELETE_CAT_REQUEST";
export const DELETE_CAT_SUCCESS = "DELETE_CAT_SUCCESS";
export const DELETE_CAT_RESET = "DELETE_CAT_RESET";
export const DELETE_CAT_FAIL = "DELETE_CAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
